backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Articles de voyage"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date de publication", name: "pubDate", widget: "datetime"}
      - {label: "Image principale", name: "heroImage", widget: "image", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}
