backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Articles de voyage"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date de publication", name: "pubDate", widget: "datetime"}
      - label: "Voyage"
        name: "voyage"
        widget: "select"
        options: 
          - {label: "Japon 2025", value: "japon-2025"}
          - {label: "Italie 2024", value: "italie-2024"}
          - {label: "Articles de Test", value: "test"}
      - {label: "Lieu", name: "lieu", widget: "string", required: false}
      - {label: "Image principale", name: "heroImage", widget: "image", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}